---
# Create an application user and grant access to authorised users

- name: create app user
  user: name="{{ core_user_app_username }}" shell=/bin/bash state=present comment="Application user"

- name: add public keys for app user
  authorized_key: user="{{ core_user_app_username }}" key="{{ lookup('file',item) }}"
  with_fileglob:
  - "{{ core_user_app_authorized_keys_directory }}/*"
  when: core_enable_feature_user_app_create_authorized_keys_file == true

- include: users-common.yml
  vars:
    username: "{{ core_user_app_username }}"
    create_bash_aliases: "{{ core_enable_feature_user_app_create_bash_aliases }}"
