---
# Configure controller user

- name: ensure controller user is a member of the adm group
  user: name="{{ core_user_controller_username }}" groups="adm" append="yes"
  when: core_enable_feature_user_controller_add_to_adm_group == true

- include: users-common.yml
  vars:
    username: "{{ core_user_controller_username }}"
    create_bash_aliases: "{{ core_enable_feature_user_controller_create_bash_aliases }}"
