---
# Configure VM for use

- name: update package lists
  apt: update_cache=yes

- include: sudo-config.yml

- include: ssh-config.yml

- include: swap-file.yml
  when: core_swap_file_enabled == true

- include: ssl-private-key.yml
  when: core_ssl_private_key_enabled == true

- include: controller-user.yml
  when: core_controller_user_enabled == true
- include: app-user.yml
  when: core_app_user_enabled == true
