---
# Configure VM for use

# System configuration

- include: update-packages.yml

- include: swap-file.yml
  when: core_enable_feature_create_swap_file == true

# Services configuration

- include: ssh-known-hosts.yml
  when: core_enable_feature_ssh_manage_known_hosts == true

# Users configuration

- include: controller-user.yml
  when: core_enable_feature_user_create_controller == true

- include: app-user.yml
  when: core_enable_feature_user_create_app == true
