---
# Configure SSH

- name: add ssh known_hosts file
  file: path=/etc/ssh/ssh_known_hosts state=touch
- name: add hosts to ssh known_hosts
  template: src=etc/ssh/ssh_known_hosts.j2 dest=/etc/ssh/ssh_known_hosts owner=root group=root mode=644
