---
# Configure SSH

- name: add known hosts to SSH known hosts file
  lineinfile: dest=/etc/ssh/ssh_known_hosts line="{{ item.line }}" insertafter=EOF state=present create=yes
  with_items: core_ssh_known_hosts
