---

- name: copy ssl private key to secure location
  copy: src="{{ core_ssl_private_key_source_path }}/{{ core_ssl_private_key_source_file }}" dest="{{ core_ssl_private_key_destination_path }}/{{ core_ssl_private_key_destination_file }}" owner=root group=root mode=600
