---
# Common setup for all users

- name: determine if bash_aliases file exists for user
  stat: path="/home/{{ username }}/.bash_aliases"
  register: core_fact_user_bash_aliases_exist
  when: create_bash_aliases == true or create_bash_aliases == "True"

- name: ensure bash_aliases file exists for user
  file: path="/home/{{ username }}/.bash_aliases" group="{{ username }}" owner="{{ username }}" state=touch
  when: (create_bash_aliases == true or create_bash_aliases == "True") and core_fact_user_bash_aliases_exist.stat.exists == false

- name: determine if rnd file exists for user
  stat: path="/home/{{ username }}/.rnd"
  register: core_fact_user_rnd_exist

- name: ensure rnd file exists for user
  file: path="/home/{{ username }}/.rnd" group="{{ username }}" owner="{{ username }}" state=touch
  when: core_fact_user_rnd_exist.stat.exists == false
